

title: Portfolio Fotográfico de José Antonio Gil Valencia
email: gilvalencia86@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Portfolio Fotográfico_Diferentes Técnicas de Inmersión Fotográfica.

baseurl: "portfolio_fotoBlog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: chdezreyes
github_username:  gilvalencia
instagram_username: jagilvalencia
instagram_url: "https://www.instagram.com/jagilvalencia/"
500px_username: gilvalencia
500px_url: "https://500px.com/p/gilvalencia?view=photos"

# Build settings
theme: minima
plugins:
  - jekyll-feed
